/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.DialMyCalls.Api;
using IO.DialMyCalls.Model;
using IO.DialMyCalls.Client;
using System.Reflection;

namespace IO.DialMyCalls.Test
{
    /// <summary>
    ///  Class for testing CallRecipient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CallRecipientTests
    {
        // TODO uncomment below to declare an instance variable for CallRecipient
        //private CallRecipient instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CallRecipient
            //instance = new CallRecipient();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CallRecipient
        /// </summary>
        [Test]
        public void CallRecipientInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CallRecipient
            //Assert.IsInstanceOfType<CallRecipient> (instance, "variable 'instance' is a CallRecipient");
        }

        /// <summary>
        /// Test the property 'Firstname'
        /// </summary>
        [Test]
        public void FirstnameTest()
        {
            // TODO unit test for the property 'Firstname'
        }
        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Test]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }
        /// <summary>
        /// Test the property 'Miscellaneous'
        /// </summary>
        [Test]
        public void MiscellaneousTest()
        {
            // TODO unit test for the property 'Miscellaneous'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Extension'
        /// </summary>
        [Test]
        public void ExtensionTest()
        {
            // TODO unit test for the property 'Extension'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Test]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
        /// <summary>
        /// Test the property 'AddOn'
        /// </summary>
        [Test]
        public void AddOnTest()
        {
            // TODO unit test for the property 'AddOn'
        }
        /// <summary>
        /// Test the property 'Attempts'
        /// </summary>
        [Test]
        public void AttemptsTest()
        {
            // TODO unit test for the property 'Attempts'
        }
        /// <summary>
        /// Test the property 'Successful'
        /// </summary>
        [Test]
        public void SuccessfulTest()
        {
            // TODO unit test for the property 'Successful'
        }
        /// <summary>
        /// Test the property 'CalledAt'
        /// </summary>
        [Test]
        public void CalledAtTest()
        {
            // TODO unit test for the property 'CalledAt'
        }

    }

}
