/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.DialMyCalls.Api;
using IO.DialMyCalls.Model;
using IO.DialMyCalls.Client;
using System.Reflection;

namespace IO.DialMyCalls.Test
{
    /// <summary>
    ///  Class for testing Callservice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CallserviceTests
    {
        // TODO uncomment below to declare an instance variable for Callservice
        //private Callservice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Callservice
            //instance = new Callservice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Callservice
        /// </summary>
        [Test]
        public void CallserviceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Callservice
            //Assert.IsInstanceOfType<Callservice> (instance, "variable 'instance' is a Callservice");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AccessaccountId'
        /// </summary>
        [Test]
        public void AccessaccountIdTest()
        {
            // TODO unit test for the property 'AccessaccountId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RecordingId'
        /// </summary>
        [Test]
        public void RecordingIdTest()
        {
            // TODO unit test for the property 'RecordingId'
        }
        /// <summary>
        /// Test the property 'PendingCancel'
        /// </summary>
        [Test]
        public void PendingCancelTest()
        {
            // TODO unit test for the property 'PendingCancel'
        }
        /// <summary>
        /// Test the property 'CreditCost'
        /// </summary>
        [Test]
        public void CreditCostTest()
        {
            // TODO unit test for the property 'CreditCost'
        }
        /// <summary>
        /// Test the property 'TotalRecipients'
        /// </summary>
        [Test]
        public void TotalRecipientsTest()
        {
            // TODO unit test for the property 'TotalRecipients'
        }
        /// <summary>
        /// Test the property 'SendAt'
        /// </summary>
        [Test]
        public void SendAtTest()
        {
            // TODO unit test for the property 'SendAt'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
