/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.DialMyCalls.Api;
using IO.DialMyCalls.Model;
using IO.DialMyCalls.Client;
using System.Reflection;

namespace IO.DialMyCalls.Test
{
    /// <summary>
    ///  Class for testing CreateTextParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateTextParametersTests
    {
        // TODO uncomment below to declare an instance variable for CreateTextParameters
        //private CreateTextParameters instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateTextParameters
            //instance = new CreateTextParameters();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateTextParameters
        /// </summary>
        [Test]
        public void CreateTextParametersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateTextParameters
            //Assert.IsInstanceOfType<CreateTextParameters> (instance, "variable 'instance' is a CreateTextParameters");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'KeywordId'
        /// </summary>
        [Test]
        public void KeywordIdTest()
        {
            // TODO unit test for the property 'KeywordId'
        }
        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Test]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
        /// <summary>
        /// Test the property 'SendAt'
        /// </summary>
        [Test]
        public void SendAtTest()
        {
            // TODO unit test for the property 'SendAt'
        }
        /// <summary>
        /// Test the property 'SendImmediately'
        /// </summary>
        [Test]
        public void SendImmediatelyTest()
        {
            // TODO unit test for the property 'SendImmediately'
        }
        /// <summary>
        /// Test the property 'SendEmail'
        /// </summary>
        [Test]
        public void SendEmailTest()
        {
            // TODO unit test for the property 'SendEmail'
        }
        /// <summary>
        /// Test the property 'AccessaccountId'
        /// </summary>
        [Test]
        public void AccessaccountIdTest()
        {
            // TODO unit test for the property 'AccessaccountId'
        }
        /// <summary>
        /// Test the property 'ShortcodeId'
        /// </summary>
        [Test]
        public void ShortcodeIdTest()
        {
            // TODO unit test for the property 'ShortcodeId'
        }
        /// <summary>
        /// Test the property 'ConcatenateSms'
        /// </summary>
        [Test]
        public void ConcatenateSmsTest()
        {
            // TODO unit test for the property 'ConcatenateSms'
        }
        /// <summary>
        /// Test the property 'Contacts'
        /// </summary>
        [Test]
        public void ContactsTest()
        {
            // TODO unit test for the property 'Contacts'
        }

    }

}
