/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.DialMyCalls.Api;
using IO.DialMyCalls.Model;
using IO.DialMyCalls.Client;
using System.Reflection;

namespace IO.DialMyCalls.Test
{
    /// <summary>
    ///  Class for testing CreateRecordingByPhoneParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateRecordingByPhoneParametersTests
    {
        // TODO uncomment below to declare an instance variable for CreateRecordingByPhoneParameters
        //private CreateRecordingByPhoneParameters instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateRecordingByPhoneParameters
            //instance = new CreateRecordingByPhoneParameters();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateRecordingByPhoneParameters
        /// </summary>
        [Test]
        public void CreateRecordingByPhoneParametersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateRecordingByPhoneParameters
            //Assert.IsInstanceOfType<CreateRecordingByPhoneParameters> (instance, "variable 'instance' is a CreateRecordingByPhoneParameters");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CalleridId'
        /// </summary>
        [Test]
        public void CalleridIdTest()
        {
            // TODO unit test for the property 'CalleridId'
        }
        /// <summary>
        /// Test the property 'Whitelabel'
        /// </summary>
        [Test]
        public void WhitelabelTest()
        {
            // TODO unit test for the property 'Whitelabel'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Extension'
        /// </summary>
        [Test]
        public void ExtensionTest()
        {
            // TODO unit test for the property 'Extension'
        }

    }

}
