/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.DialMyCalls.Api;
using IO.DialMyCalls.Model;
using IO.DialMyCalls.Client;
using System.Reflection;

namespace IO.DialMyCalls.Test
{
    /// <summary>
    ///  Class for testing PushToTalk
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PushToTalkTests
    {
        // TODO uncomment below to declare an instance variable for PushToTalk
        //private PushToTalk instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PushToTalk
            //instance = new PushToTalk();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PushToTalk
        /// </summary>
        [Test]
        public void PushToTalkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PushToTalk
            //Assert.IsInstanceOfType<PushToTalk> (instance, "variable 'instance' is a PushToTalk");
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'CalleridId'
        /// </summary>
        [Test]
        public void CalleridIdTest()
        {
            // TODO unit test for the property 'CalleridId'
        }
        /// <summary>
        /// Test the property 'Ringtone'
        /// </summary>
        [Test]
        public void RingtoneTest()
        {
            // TODO unit test for the property 'Ringtone'
        }
        /// <summary>
        /// Test the property 'Cpm'
        /// </summary>
        [Test]
        public void CpmTest()
        {
            // TODO unit test for the property 'Cpm'
        }
        /// <summary>
        /// Test the property 'AddMessage'
        /// </summary>
        [Test]
        public void AddMessageTest()
        {
            // TODO unit test for the property 'AddMessage'
        }

    }

}
