/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.DialMyCalls.Api;
using IO.DialMyCalls.Model;
using IO.DialMyCalls.Client;
using System.Reflection;

namespace IO.DialMyCalls.Test
{
    /// <summary>
    ///  Class for testing UpdateAccessAccountByIdParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateAccessAccountByIdParametersTests
    {
        // TODO uncomment below to declare an instance variable for UpdateAccessAccountByIdParameters
        //private UpdateAccessAccountByIdParameters instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateAccessAccountByIdParameters
            //instance = new UpdateAccessAccountByIdParameters();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateAccessAccountByIdParameters
        /// </summary>
        [Test]
        public void UpdateAccessAccountByIdParametersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateAccessAccountByIdParameters
            //Assert.IsInstanceOfType<UpdateAccessAccountByIdParameters> (instance, "variable 'instance' is a UpdateAccessAccountByIdParameters");
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
