/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.DialMyCalls.Api;
using IO.DialMyCalls.Model;
using IO.DialMyCalls.Client;
using System.Reflection;

namespace IO.DialMyCalls.Test
{
    /// <summary>
    ///  Class for testing UpdateVanityNumberByIdParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateVanityNumberByIdParametersTests
    {
        // TODO uncomment below to declare an instance variable for UpdateVanityNumberByIdParameters
        //private UpdateVanityNumberByIdParameters instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateVanityNumberByIdParameters
            //instance = new UpdateVanityNumberByIdParameters();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateVanityNumberByIdParameters
        /// </summary>
        [Test]
        public void UpdateVanityNumberByIdParametersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateVanityNumberByIdParameters
            //Assert.IsInstanceOfType<UpdateVanityNumberByIdParameters> (instance, "variable 'instance' is a UpdateVanityNumberByIdParameters");
        }

        /// <summary>
        /// Test the property 'CallOptions'
        /// </summary>
        [Test]
        public void CallOptionsTest()
        {
            // TODO unit test for the property 'CallOptions'
        }
        /// <summary>
        /// Test the property 'RecordingSource'
        /// </summary>
        [Test]
        public void RecordingSourceTest()
        {
            // TODO unit test for the property 'RecordingSource'
        }
        /// <summary>
        /// Test the property 'SpecificRecordingId'
        /// </summary>
        [Test]
        public void SpecificRecordingIdTest()
        {
            // TODO unit test for the property 'SpecificRecordingId'
        }
        /// <summary>
        /// Test the property 'PlayCta'
        /// </summary>
        [Test]
        public void PlayCtaTest()
        {
            // TODO unit test for the property 'PlayCta'
        }
        /// <summary>
        /// Test the property 'PttNumberId'
        /// </summary>
        [Test]
        public void PttNumberIdTest()
        {
            // TODO unit test for the property 'PttNumberId'
        }

    }

}
