/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.DialMyCalls.Api;
using IO.DialMyCalls.Model;
using IO.DialMyCalls.Client;
using System.Reflection;

namespace IO.DialMyCalls.Test
{
    /// <summary>
    ///  Class for testing Vanitynumber
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VanitynumberTests
    {
        // TODO uncomment below to declare an instance variable for Vanitynumber
        //private Vanitynumber instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Vanitynumber
            //instance = new Vanitynumber();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Vanitynumber
        /// </summary>
        [Test]
        public void VanitynumberInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Vanitynumber
            //Assert.IsInstanceOfType<Vanitynumber> (instance, "variable 'instance' is a Vanitynumber");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'MinutesUsed'
        /// </summary>
        [Test]
        public void MinutesUsedTest()
        {
            // TODO unit test for the property 'MinutesUsed'
        }
        /// <summary>
        /// Test the property 'MinutesAllowed'
        /// </summary>
        [Test]
        public void MinutesAllowedTest()
        {
            // TODO unit test for the property 'MinutesAllowed'
        }
        /// <summary>
        /// Test the property 'VoicemailsNew'
        /// </summary>
        [Test]
        public void VoicemailsNewTest()
        {
            // TODO unit test for the property 'VoicemailsNew'
        }
        /// <summary>
        /// Test the property 'VoicemailsOld'
        /// </summary>
        [Test]
        public void VoicemailsOldTest()
        {
            // TODO unit test for the property 'VoicemailsOld'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
