/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.DialMyCalls.Client;
using IO.DialMyCalls.Api;
using IO.DialMyCalls.Model;

namespace IO.DialMyCalls.Test
{
    /// <summary>
    ///  Class for testing CallerIds
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CallerIdsTests
    {
        private CallerIds instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CallerIds();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CallerIds
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CallerIds
            //Assert.IsInstanceOfType(typeof(CallerIds), instance, "instance is a CallerIds");
        }

        
        /// <summary>
        /// Test CreateCallerId
        /// </summary>
        [Test]
        public void CreateCallerIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateCallerIdParameters createCallerIdParameters = null;
            //var response = instance.CreateCallerId(createCallerIdParameters);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test CreateUnverifiedCallerId
        /// </summary>
        [Test]
        public void CreateUnverifiedCallerIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateUnverifiedCallerIdParameters createUnverifiedCallerIdParameters = null;
            //var response = instance.CreateUnverifiedCallerId(createUnverifiedCallerIdParameters);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test DeleteCallerIdById
        /// </summary>
        [Test]
        public void DeleteCallerIdByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string calleridId = null;
            //var response = instance.DeleteCallerIdById(calleridId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test GetCallerIdById
        /// </summary>
        [Test]
        public void GetCallerIdByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string calleridId = null;
            //var response = instance.GetCallerIdById(calleridId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test GetCallerIds
        /// </summary>
        [Test]
        public void GetCallerIdsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string range = null;
            //var response = instance.GetCallerIds(range);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test UpdateCallerIdById
        /// </summary>
        [Test]
        public void UpdateCallerIdByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UpdateCallerIdByIdParameters updateCallerIdByIdParameters = null;
            //string calleridId = null;
            //var response = instance.UpdateCallerIdById(updateCallerIdByIdParameters, calleridId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test VerifyCallerIdById
        /// </summary>
        [Test]
        public void VerifyCallerIdByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //VerifyCallerIdByIdParameters verifyCallerIdByIdParameters = null;
            //string calleridId = null;
            //var response = instance.VerifyCallerIdById(verifyCallerIdByIdParameters, calleridId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
    }

}
