/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.DialMyCalls.Client;
using IO.DialMyCalls.Api;
using IO.DialMyCalls.Model;

namespace IO.DialMyCalls.Test
{
    /// <summary>
    ///  Class for testing Recordings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RecordingsTests
    {
        private Recordings instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Recordings();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Recordings
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' Recordings
            //Assert.IsInstanceOfType(typeof(Recordings), instance, "instance is a Recordings");
        }

        
        /// <summary>
        /// Test CreateRecording
        /// </summary>
        [Test]
        public void CreateRecordingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateRecordingParameters createRecordingParameters = null;
            //var response = instance.CreateRecording(createRecordingParameters);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test CreateRecordingByPhone
        /// </summary>
        [Test]
        public void CreateRecordingByPhoneTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateRecordingByPhoneParameters createRecordingByPhoneParameters = null;
            //var response = instance.CreateRecordingByPhone(createRecordingByPhoneParameters);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test CreateRecordingByUrl
        /// </summary>
        [Test]
        public void CreateRecordingByUrlTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateRecordingByUrlParameters createRecordingByUrlParameters = null;
            //var response = instance.CreateRecordingByUrl(createRecordingByUrlParameters);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test DeleteRecordingById
        /// </summary>
        [Test]
        public void DeleteRecordingByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recordingId = null;
            //var response = instance.DeleteRecordingById(recordingId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test GetRecordingById
        /// </summary>
        [Test]
        public void GetRecordingByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string recordingId = null;
            //var response = instance.GetRecordingById(recordingId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test GetRecordings
        /// </summary>
        [Test]
        public void GetRecordingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string range = null;
            //var response = instance.GetRecordings(range);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test UpdateRecordingById
        /// </summary>
        [Test]
        public void UpdateRecordingByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UpdateRecordingByIdParameters updateRecordingByIdParameters = null;
            //string recordingId = null;
            //var response = instance.UpdateRecordingById(updateRecordingByIdParameters, recordingId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
    }

}
