/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.DialMyCalls.Client;
using IO.DialMyCalls.Api;
using IO.DialMyCalls.Model;

namespace IO.DialMyCalls.Test
{
    /// <summary>
    ///  Class for testing Texts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TextsTests
    {
        private Texts instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new Texts();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Texts
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' Texts
            //Assert.IsInstanceOfType(typeof(Texts), instance, "instance is a Texts");
        }

        
        /// <summary>
        /// Test CancelTextById
        /// </summary>
        [Test]
        public void CancelTextByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string textId = null;
            //var response = instance.CancelTextById(textId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test CreateText
        /// </summary>
        [Test]
        public void CreateTextTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateTextParameters createTextParameters = null;
            //var response = instance.CreateText(createTextParameters);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test DeleteIncomingTextById
        /// </summary>
        [Test]
        public void DeleteIncomingTextByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string textId = null;
            //var response = instance.DeleteIncomingTextById(textId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test GetIncomingTextById
        /// </summary>
        [Test]
        public void GetIncomingTextByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string textId = null;
            //var response = instance.GetIncomingTextById(textId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test GetIncomingTexts
        /// </summary>
        [Test]
        public void GetIncomingTextsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string range = null;
            //var response = instance.GetIncomingTexts(range);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test GetShortCodes
        /// </summary>
        [Test]
        public void GetShortCodesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string range = null;
            //var response = instance.GetShortCodes(range);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test GetTextById
        /// </summary>
        [Test]
        public void GetTextByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string textId = null;
            //var response = instance.GetTextById(textId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test GetTextRecipientsByTextId
        /// </summary>
        [Test]
        public void GetTextRecipientsByTextIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string textId = null;
            //string range = null;
            //var response = instance.GetTextRecipientsByTextId(textId, range);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test GetTexts
        /// </summary>
        [Test]
        public void GetTextsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string range = null;
            //var response = instance.GetTexts(range);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
    }

}
