/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.DialMyCalls.Model
{
    /// <summary>
    /// CallRecipient
    /// </summary>
    [DataContract]
    public partial class CallRecipient :  IEquatable<CallRecipient>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CallRecipient" /> class.
        /// </summary>
        /// <param name="Firstname">The recipient&#39;s first name..</param>
        /// <param name="Lastname">The recipient&#39;s last name..</param>
        /// <param name="Miscellaneous">Miscellaneous information..</param>
        /// <param name="Email">The recipient&#39;s email address..</param>
        /// <param name="Phone">The recipient&#39;s phone number..</param>
        /// <param name="Extension">The recipient&#39;s phone extension..</param>
        /// <param name="Status">Status of the call. Options: live_answer, vm, busy, no_answer, dialing, not_connected, queued.</param>
        /// <param name="Duration">Duration of the call in seconds..</param>
        /// <param name="AddOn">Result from add-on feature..</param>
        /// <param name="Attempts">Number of attempts to call was made..</param>
        /// <param name="Successful">Whether the call was successful or not..</param>
        /// <param name="CalledAt">When the recipient was contacted..</param>
        public CallRecipient(string Firstname = null, string Lastname = null, string Miscellaneous = null, string Email = null, string Phone = null, string Extension = null, string Status = null, int? Duration = null, string AddOn = null, string Attempts = null, bool? Successful = null, string CalledAt = null)
        {
            this.Firstname = Firstname;
            this.Lastname = Lastname;
            this.Miscellaneous = Miscellaneous;
            this.Email = Email;
            this.Phone = Phone;
            this.Extension = Extension;
            this.Status = Status;
            this.Duration = Duration;
            this.AddOn = AddOn;
            this.Attempts = Attempts;
            this.Successful = Successful;
            this.CalledAt = CalledAt;
        }
        
        /// <summary>
        /// The recipient&#39;s first name.
        /// </summary>
        /// <value>The recipient&#39;s first name.</value>
        [DataMember(Name="firstname", EmitDefaultValue=false)]
        public string Firstname { get; set; }
        /// <summary>
        /// The recipient&#39;s last name.
        /// </summary>
        /// <value>The recipient&#39;s last name.</value>
        [DataMember(Name="lastname", EmitDefaultValue=false)]
        public string Lastname { get; set; }
        /// <summary>
        /// Miscellaneous information.
        /// </summary>
        /// <value>Miscellaneous information.</value>
        [DataMember(Name="miscellaneous", EmitDefaultValue=false)]
        public string Miscellaneous { get; set; }
        /// <summary>
        /// The recipient&#39;s email address.
        /// </summary>
        /// <value>The recipient&#39;s email address.</value>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }
        /// <summary>
        /// The recipient&#39;s phone number.
        /// </summary>
        /// <value>The recipient&#39;s phone number.</value>
        [DataMember(Name="phone", EmitDefaultValue=false)]
        public string Phone { get; set; }
        /// <summary>
        /// The recipient&#39;s phone extension.
        /// </summary>
        /// <value>The recipient&#39;s phone extension.</value>
        [DataMember(Name="extension", EmitDefaultValue=false)]
        public string Extension { get; set; }
        /// <summary>
        /// Status of the call. Options: live_answer, vm, busy, no_answer, dialing, not_connected, queued
        /// </summary>
        /// <value>Status of the call. Options: live_answer, vm, busy, no_answer, dialing, not_connected, queued</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }
        /// <summary>
        /// Duration of the call in seconds.
        /// </summary>
        /// <value>Duration of the call in seconds.</value>
        [DataMember(Name="duration", EmitDefaultValue=false)]
        public int? Duration { get; set; }
        /// <summary>
        /// Result from add-on feature.
        /// </summary>
        /// <value>Result from add-on feature.</value>
        [DataMember(Name="add_on", EmitDefaultValue=false)]
        public string AddOn { get; set; }
        /// <summary>
        /// Number of attempts to call was made.
        /// </summary>
        /// <value>Number of attempts to call was made.</value>
        [DataMember(Name="attempts", EmitDefaultValue=false)]
        public string Attempts { get; set; }
        /// <summary>
        /// Whether the call was successful or not.
        /// </summary>
        /// <value>Whether the call was successful or not.</value>
        [DataMember(Name="successful", EmitDefaultValue=false)]
        public bool? Successful { get; set; }
        /// <summary>
        /// When the recipient was contacted.
        /// </summary>
        /// <value>When the recipient was contacted.</value>
        [DataMember(Name="called_at", EmitDefaultValue=false)]
        public string CalledAt { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CallRecipient {\n");
            sb.Append("  Firstname: ").Append(Firstname).Append("\n");
            sb.Append("  Lastname: ").Append(Lastname).Append("\n");
            sb.Append("  Miscellaneous: ").Append(Miscellaneous).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  Extension: ").Append(Extension).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("  AddOn: ").Append(AddOn).Append("\n");
            sb.Append("  Attempts: ").Append(Attempts).Append("\n");
            sb.Append("  Successful: ").Append(Successful).Append("\n");
            sb.Append("  CalledAt: ").Append(CalledAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CallRecipient);
        }

        /// <summary>
        /// Returns true if CallRecipient instances are equal
        /// </summary>
        /// <param name="other">Instance of CallRecipient to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CallRecipient other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Firstname == other.Firstname ||
                    this.Firstname != null &&
                    this.Firstname.Equals(other.Firstname)
                ) && 
                (
                    this.Lastname == other.Lastname ||
                    this.Lastname != null &&
                    this.Lastname.Equals(other.Lastname)
                ) && 
                (
                    this.Miscellaneous == other.Miscellaneous ||
                    this.Miscellaneous != null &&
                    this.Miscellaneous.Equals(other.Miscellaneous)
                ) && 
                (
                    this.Email == other.Email ||
                    this.Email != null &&
                    this.Email.Equals(other.Email)
                ) && 
                (
                    this.Phone == other.Phone ||
                    this.Phone != null &&
                    this.Phone.Equals(other.Phone)
                ) && 
                (
                    this.Extension == other.Extension ||
                    this.Extension != null &&
                    this.Extension.Equals(other.Extension)
                ) && 
                (
                    this.Status == other.Status ||
                    this.Status != null &&
                    this.Status.Equals(other.Status)
                ) && 
                (
                    this.Duration == other.Duration ||
                    this.Duration != null &&
                    this.Duration.Equals(other.Duration)
                ) && 
                (
                    this.AddOn == other.AddOn ||
                    this.AddOn != null &&
                    this.AddOn.Equals(other.AddOn)
                ) && 
                (
                    this.Attempts == other.Attempts ||
                    this.Attempts != null &&
                    this.Attempts.Equals(other.Attempts)
                ) && 
                (
                    this.Successful == other.Successful ||
                    this.Successful != null &&
                    this.Successful.Equals(other.Successful)
                ) && 
                (
                    this.CalledAt == other.CalledAt ||
                    this.CalledAt != null &&
                    this.CalledAt.Equals(other.CalledAt)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Firstname != null)
                    hash = hash * 59 + this.Firstname.GetHashCode();
                if (this.Lastname != null)
                    hash = hash * 59 + this.Lastname.GetHashCode();
                if (this.Miscellaneous != null)
                    hash = hash * 59 + this.Miscellaneous.GetHashCode();
                if (this.Email != null)
                    hash = hash * 59 + this.Email.GetHashCode();
                if (this.Phone != null)
                    hash = hash * 59 + this.Phone.GetHashCode();
                if (this.Extension != null)
                    hash = hash * 59 + this.Extension.GetHashCode();
                if (this.Status != null)
                    hash = hash * 59 + this.Status.GetHashCode();
                if (this.Duration != null)
                    hash = hash * 59 + this.Duration.GetHashCode();
                if (this.AddOn != null)
                    hash = hash * 59 + this.AddOn.GetHashCode();
                if (this.Attempts != null)
                    hash = hash * 59 + this.Attempts.GetHashCode();
                if (this.Successful != null)
                    hash = hash * 59 + this.Successful.GetHashCode();
                if (this.CalledAt != null)
                    hash = hash * 59 + this.CalledAt.GetHashCode();
                return hash;
            }
        }
    }

}
