/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace IO.DialMyCalls.Model
{
    /// <summary>
    /// Service
    /// </summary>
    [DataContract]
    public partial class Service :  IEquatable<Service>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Service" /> class.
        /// </summary>
        /// <param name="Id">Unique identifier for this service..</param>
        /// <param name="AccessaccountId">Unique identifier for the access account which initiated this if available..</param>
        /// <param name="Name">The name of the service..</param>
        /// <param name="PendingCancel">Whether the service has been flagged to be cancelled..</param>
        /// <param name="CreditCost">The amount of credits required to schedule this service..</param>
        /// <param name="TotalRecipients">The amount of recipients for this service..</param>
        /// <param name="SendAt">When the service will be sent..</param>
        /// <param name="CreatedAt">When the service was created..</param>
        /// <param name="UpdatedAt">When the service was last updated..</param>
        public Service(Guid? Id = null, Guid? AccessaccountId = null, string Name = null, bool? PendingCancel = null, float? CreditCost = null, decimal? TotalRecipients = null, string SendAt = null, string CreatedAt = null, string UpdatedAt = null)
        {
            this.Id = Id;
            this.AccessaccountId = AccessaccountId;
            this.Name = Name;
            this.PendingCancel = PendingCancel;
            this.CreditCost = CreditCost;
            this.TotalRecipients = TotalRecipients;
            this.SendAt = SendAt;
            this.CreatedAt = CreatedAt;
            this.UpdatedAt = UpdatedAt;
        }
        
        /// <summary>
        /// Unique identifier for this service.
        /// </summary>
        /// <value>Unique identifier for this service.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public Guid? Id { get; set; }
        /// <summary>
        /// Unique identifier for the access account which initiated this if available.
        /// </summary>
        /// <value>Unique identifier for the access account which initiated this if available.</value>
        [DataMember(Name="accessaccount_id", EmitDefaultValue=false)]
        public Guid? AccessaccountId { get; set; }
        /// <summary>
        /// The name of the service.
        /// </summary>
        /// <value>The name of the service.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Whether the service has been flagged to be cancelled.
        /// </summary>
        /// <value>Whether the service has been flagged to be cancelled.</value>
        [DataMember(Name="pending_cancel", EmitDefaultValue=false)]
        public bool? PendingCancel { get; set; }
        /// <summary>
        /// The amount of credits required to schedule this service.
        /// </summary>
        /// <value>The amount of credits required to schedule this service.</value>
        [DataMember(Name="credit_cost", EmitDefaultValue=false)]
        public float? CreditCost { get; set; }
        /// <summary>
        /// The amount of recipients for this service.
        /// </summary>
        /// <value>The amount of recipients for this service.</value>
        [DataMember(Name="total_recipients", EmitDefaultValue=false)]
        public decimal? TotalRecipients { get; set; }
        /// <summary>
        /// When the service will be sent.
        /// </summary>
        /// <value>When the service will be sent.</value>
        [DataMember(Name="send_at", EmitDefaultValue=false)]
        public string SendAt { get; set; }
        /// <summary>
        /// When the service was created.
        /// </summary>
        /// <value>When the service was created.</value>
        [DataMember(Name="created_at", EmitDefaultValue=false)]
        public string CreatedAt { get; set; }
        /// <summary>
        /// When the service was last updated.
        /// </summary>
        /// <value>When the service was last updated.</value>
        [DataMember(Name="updated_at", EmitDefaultValue=false)]
        public string UpdatedAt { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Service {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  AccessaccountId: ").Append(AccessaccountId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PendingCancel: ").Append(PendingCancel).Append("\n");
            sb.Append("  CreditCost: ").Append(CreditCost).Append("\n");
            sb.Append("  TotalRecipients: ").Append(TotalRecipients).Append("\n");
            sb.Append("  SendAt: ").Append(SendAt).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Service);
        }

        /// <summary>
        /// Returns true if Service instances are equal
        /// </summary>
        /// <param name="other">Instance of Service to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Service other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.AccessaccountId == other.AccessaccountId ||
                    this.AccessaccountId != null &&
                    this.AccessaccountId.Equals(other.AccessaccountId)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.PendingCancel == other.PendingCancel ||
                    this.PendingCancel != null &&
                    this.PendingCancel.Equals(other.PendingCancel)
                ) && 
                (
                    this.CreditCost == other.CreditCost ||
                    this.CreditCost != null &&
                    this.CreditCost.Equals(other.CreditCost)
                ) && 
                (
                    this.TotalRecipients == other.TotalRecipients ||
                    this.TotalRecipients != null &&
                    this.TotalRecipients.Equals(other.TotalRecipients)
                ) && 
                (
                    this.SendAt == other.SendAt ||
                    this.SendAt != null &&
                    this.SendAt.Equals(other.SendAt)
                ) && 
                (
                    this.CreatedAt == other.CreatedAt ||
                    this.CreatedAt != null &&
                    this.CreatedAt.Equals(other.CreatedAt)
                ) && 
                (
                    this.UpdatedAt == other.UpdatedAt ||
                    this.UpdatedAt != null &&
                    this.UpdatedAt.Equals(other.UpdatedAt)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.AccessaccountId != null)
                    hash = hash * 59 + this.AccessaccountId.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.PendingCancel != null)
                    hash = hash * 59 + this.PendingCancel.GetHashCode();
                if (this.CreditCost != null)
                    hash = hash * 59 + this.CreditCost.GetHashCode();
                if (this.TotalRecipients != null)
                    hash = hash * 59 + this.TotalRecipients.GetHashCode();
                if (this.SendAt != null)
                    hash = hash * 59 + this.SendAt.GetHashCode();
                if (this.CreatedAt != null)
                    hash = hash * 59 + this.CreatedAt.GetHashCode();
                if (this.UpdatedAt != null)
                    hash = hash * 59 + this.UpdatedAt.GetHashCode();
                return hash;
            }
        }
    }

}
