/* 
 * DialMyCalls API
 *
 * The DialMyCalls API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: support@dialmycalls.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.DialMyCalls.Client;

namespace IO.DialMyCalls.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IKeywords : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete Keyword
        /// </summary>
        /// <remarks>
        /// Delete a keyword. &lt;br&gt;&lt;br&gt; Returns the following if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X DELETE https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>Object</returns>
        Object DeleteKeywordByID (string keywordId);

        /// <summary>
        /// Delete Keyword
        /// </summary>
        /// <remarks>
        /// Delete a keyword. &lt;br&gt;&lt;br&gt; Returns the following if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X DELETE https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> DeleteKeywordByIDWithHttpInfo (string keywordId);
        /// <summary>
        /// Get Keyword
        /// </summary>
        /// <remarks>
        /// Retrieve a keyword. &lt;br&gt;&lt;br&gt; Returns a keyword object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>Object</returns>
        Object GetKeywordByID (string keywordId);

        /// <summary>
        /// Get Keyword
        /// </summary>
        /// <remarks>
        /// Retrieve a keyword. &lt;br&gt;&lt;br&gt; Returns a keyword object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> GetKeywordByIDWithHttpInfo (string keywordId);
        /// <summary>
        /// List Keywords
        /// </summary>
        /// <remarks>
        /// Retrieve a list of keywords. &lt;br&gt;&lt;br&gt; Returns a list of keyword objects. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keywords &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="range">Range (ie \&quot;records&#x3D;201-300\&quot;) of keywords requested (optional)</param>
        /// <returns>Object</returns>
        Object GetKeywords (string range = null);

        /// <summary>
        /// List Keywords
        /// </summary>
        /// <remarks>
        /// Retrieve a list of keywords. &lt;br&gt;&lt;br&gt; Returns a list of keyword objects. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keywords &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="range">Range (ie \&quot;records&#x3D;201-300\&quot;) of keywords requested (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> GetKeywordsWithHttpInfo (string range = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Delete Keyword
        /// </summary>
        /// <remarks>
        /// Delete a keyword. &lt;br&gt;&lt;br&gt; Returns the following if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X DELETE https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> DeleteKeywordByIDAsync (string keywordId);

        /// <summary>
        /// Delete Keyword
        /// </summary>
        /// <remarks>
        /// Delete a keyword. &lt;br&gt;&lt;br&gt; Returns the following if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X DELETE https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteKeywordByIDAsyncWithHttpInfo (string keywordId);
        /// <summary>
        /// Get Keyword
        /// </summary>
        /// <remarks>
        /// Retrieve a keyword. &lt;br&gt;&lt;br&gt; Returns a keyword object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> GetKeywordByIDAsync (string keywordId);

        /// <summary>
        /// Get Keyword
        /// </summary>
        /// <remarks>
        /// Retrieve a keyword. &lt;br&gt;&lt;br&gt; Returns a keyword object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GetKeywordByIDAsyncWithHttpInfo (string keywordId);
        /// <summary>
        /// List Keywords
        /// </summary>
        /// <remarks>
        /// Retrieve a list of keywords. &lt;br&gt;&lt;br&gt; Returns a list of keyword objects. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keywords &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="range">Range (ie \&quot;records&#x3D;201-300\&quot;) of keywords requested (optional)</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> GetKeywordsAsync (string range = null);

        /// <summary>
        /// List Keywords
        /// </summary>
        /// <remarks>
        /// Retrieve a list of keywords. &lt;br&gt;&lt;br&gt; Returns a list of keyword objects. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keywords &#x60;&#x60;&#x60;
        /// </remarks>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="range">Range (ie \&quot;records&#x3D;201-300\&quot;) of keywords requested (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GetKeywordsAsyncWithHttpInfo (string range = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class Keywords : IKeywords
    {
        private IO.DialMyCalls.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="Keywords"/> class.
        /// </summary>
        /// <returns></returns>
        public Keywords(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = IO.DialMyCalls.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Keywords"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public Keywords(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.DialMyCalls.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.DialMyCalls.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Delete Keyword Delete a keyword. &lt;br&gt;&lt;br&gt; Returns the following if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X DELETE https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>Object</returns>
        public Object DeleteKeywordByID (string keywordId)
        {
             ApiResponse<Object> localVarResponse = DeleteKeywordByIDWithHttpInfo(keywordId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Keyword Delete a keyword. &lt;br&gt;&lt;br&gt; Returns the following if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X DELETE https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > DeleteKeywordByIDWithHttpInfo (string keywordId)
        {
            // verify the required parameter 'keywordId' is set
            if (keywordId == null)
                throw new ApiException(400, "Missing required parameter 'keywordId' when calling Keywords->DeleteKeywordByID");

            var localVarPath = "/keyword/{KeywordId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (keywordId != null) localVarPathParams.Add("KeywordId", Configuration.ApiClient.ParameterToString(keywordId)); // path parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("X-Auth-ApiKey")))
            {
                localVarHeaderParams["X-Auth-ApiKey"] = Configuration.GetApiKeyWithPrefix("X-Auth-ApiKey");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteKeywordByID", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
            
        }

        /// <summary>
        /// Delete Keyword Delete a keyword. &lt;br&gt;&lt;br&gt; Returns the following if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X DELETE https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> DeleteKeywordByIDAsync (string keywordId)
        {
             ApiResponse<Object> localVarResponse = await DeleteKeywordByIDAsyncWithHttpInfo(keywordId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete Keyword Delete a keyword. &lt;br&gt;&lt;br&gt; Returns the following if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X DELETE https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteKeywordByIDAsyncWithHttpInfo (string keywordId)
        {
            // verify the required parameter 'keywordId' is set
            if (keywordId == null)
                throw new ApiException(400, "Missing required parameter 'keywordId' when calling Keywords->DeleteKeywordByID");

            var localVarPath = "/keyword/{KeywordId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (keywordId != null) localVarPathParams.Add("KeywordId", Configuration.ApiClient.ParameterToString(keywordId)); // path parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("X-Auth-ApiKey")))
            {
                localVarHeaderParams["X-Auth-ApiKey"] = Configuration.GetApiKeyWithPrefix("X-Auth-ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteKeywordByID", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
            
        }

        /// <summary>
        /// Get Keyword Retrieve a keyword. &lt;br&gt;&lt;br&gt; Returns a keyword object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>Object</returns>
        public Object GetKeywordByID (string keywordId)
        {
             ApiResponse<Object> localVarResponse = GetKeywordByIDWithHttpInfo(keywordId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Keyword Retrieve a keyword. &lt;br&gt;&lt;br&gt; Returns a keyword object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > GetKeywordByIDWithHttpInfo (string keywordId)
        {
            // verify the required parameter 'keywordId' is set
            if (keywordId == null)
                throw new ApiException(400, "Missing required parameter 'keywordId' when calling Keywords->GetKeywordByID");

            var localVarPath = "/keyword/{KeywordId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (keywordId != null) localVarPathParams.Add("KeywordId", Configuration.ApiClient.ParameterToString(keywordId)); // path parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("X-Auth-ApiKey")))
            {
                localVarHeaderParams["X-Auth-ApiKey"] = Configuration.GetApiKeyWithPrefix("X-Auth-ApiKey");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetKeywordByID", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
            
        }

        /// <summary>
        /// Get Keyword Retrieve a keyword. &lt;br&gt;&lt;br&gt; Returns a keyword object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> GetKeywordByIDAsync (string keywordId)
        {
             ApiResponse<Object> localVarResponse = await GetKeywordByIDAsyncWithHttpInfo(keywordId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Keyword Retrieve a keyword. &lt;br&gt;&lt;br&gt; Returns a keyword object if a valid identifier was provided, and returns an error otherwise. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keyword/$KEYWORD_ID &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="keywordId">KeywordId</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> GetKeywordByIDAsyncWithHttpInfo (string keywordId)
        {
            // verify the required parameter 'keywordId' is set
            if (keywordId == null)
                throw new ApiException(400, "Missing required parameter 'keywordId' when calling Keywords->GetKeywordByID");

            var localVarPath = "/keyword/{KeywordId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (keywordId != null) localVarPathParams.Add("KeywordId", Configuration.ApiClient.ParameterToString(keywordId)); // path parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("X-Auth-ApiKey")))
            {
                localVarHeaderParams["X-Auth-ApiKey"] = Configuration.GetApiKeyWithPrefix("X-Auth-ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetKeywordByID", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
            
        }

        /// <summary>
        /// List Keywords Retrieve a list of keywords. &lt;br&gt;&lt;br&gt; Returns a list of keyword objects. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keywords &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="range">Range (ie \&quot;records&#x3D;201-300\&quot;) of keywords requested (optional)</param>
        /// <returns>Object</returns>
        public Object GetKeywords (string range = null)
        {
             ApiResponse<Object> localVarResponse = GetKeywordsWithHttpInfo(range);
             return localVarResponse.Data;
        }

        /// <summary>
        /// List Keywords Retrieve a list of keywords. &lt;br&gt;&lt;br&gt; Returns a list of keyword objects. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keywords &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="range">Range (ie \&quot;records&#x3D;201-300\&quot;) of keywords requested (optional)</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > GetKeywordsWithHttpInfo (string range = null)
        {

            var localVarPath = "/keywords";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (range != null) localVarHeaderParams.Add("Range", Configuration.ApiClient.ParameterToString(range)); // header parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("X-Auth-ApiKey")))
            {
                localVarHeaderParams["X-Auth-ApiKey"] = Configuration.GetApiKeyWithPrefix("X-Auth-ApiKey");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetKeywords", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
            
        }

        /// <summary>
        /// List Keywords Retrieve a list of keywords. &lt;br&gt;&lt;br&gt; Returns a list of keyword objects. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keywords &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="range">Range (ie \&quot;records&#x3D;201-300\&quot;) of keywords requested (optional)</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> GetKeywordsAsync (string range = null)
        {
             ApiResponse<Object> localVarResponse = await GetKeywordsAsyncWithHttpInfo(range);
             return localVarResponse.Data;

        }

        /// <summary>
        /// List Keywords Retrieve a list of keywords. &lt;br&gt;&lt;br&gt; Returns a list of keyword objects. &lt;br&gt;&lt;br&gt; &#x60;&#x60;&#x60; curl -i -H \&quot;Content-Type: application/json\&quot; -X GET https://$API_KEY@api.dialmycalls.com/2.0/keywords &#x60;&#x60;&#x60;
        /// </summary>
        /// <exception cref="IO.DialMyCalls.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="range">Range (ie \&quot;records&#x3D;201-300\&quot;) of keywords requested (optional)</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> GetKeywordsAsyncWithHttpInfo (string range = null)
        {

            var localVarPath = "/keywords";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (range != null) localVarHeaderParams.Add("Range", Configuration.ApiClient.ParameterToString(range)); // header parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("X-Auth-ApiKey")))
            {
                localVarHeaderParams["X-Auth-ApiKey"] = Configuration.GetApiKeyWithPrefix("X-Auth-ApiKey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetKeywords", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Object) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
            
        }

    }
}
